pipeline {
    agent {
        docker{
            image 'maven:3-openjdk-18'
            args '-v /root/.m2:/root/.m2'
        }
    }
    environment {
        DC_WEBHOOK = credentials('GITHUB-HOOK-DEVOPS')
    }
    stages {
        stage('Build') {
            steps {
                script{
                    sh "echo generando el fragmento jar"
                    sh "mvn clean install package"
                }
            }
        }
        stage('Deploy'){
            steps {
                script{
                    sh "echo moviendo el archivo dockerfile donde está el fragmento y hacer el artifact"
                    sh "mv jobs/Dockerfile target/Dockerfile"
                    docker.withRegistry('https://registry.hub.docker.com','13ff1e12-98d9-4af3-bb62-10281237fc75'){
                        def app_version =docker.build("xhavckedx/combatdice:${env.BUILD_NUMBER}", "./target/.")
                        def app_latest = docker.build("xhavckedx/combatdice:latest", "./target/.")
                        app_version.push()
                        app_latest.push()
                    }
                }
            }
        }
    }
    post {
        success {
            archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true
            discordSend description: '''
            Build ${env.BUILD_NUMBER}
            Status: Success
            -------------- ''', footer: "[ComatDice.jar](${env.RUN_ARTIFACTS_DISPLAY_URL})", link: env.BUILD_URL, result: currentBuild.currentResult, title: JOB_NAME, webhookURL: DC_WEBHOOK
        }
    }
}
