pipeline {
    agent any
    stages {
        def app_latest
        def app_version
        stage('Build') {
            steps {
               sh "echo generando el fragmento"
               withMaven() {
                    sh "mvn clean install package"
                }
            }
        }
        stage('Deploy'){
            steps {
                script{
                    sh "echo moviendo el archivo dockerfile donde está el fragmento y hacer el artifact"
                    sh "mv jobs/Dockerfile target/Dockerfile"
                }
                docker.withRegistry('https://registry.hub.docker.com','13ff1e12-98d9-4af3-bb62-10281237fc75'){
                    app_version =docker.build("xhavckedx/combatdice:${env.BUILD_NUMBER}", "/jobs/.")
                    app_latest = docker.build("xhavckedx/combatdice:latest" "/jobs/.")
                    app_version.push()
                    app_latest.push()
                }
            }
        }
    }
    post {
        success {
            archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true
        }
    }
}
